Sylius 1.12 pristine plugin
3BRS/sylius-payment-fee-plugin pull request #5
Opened 2024-01-04 11:52 UTC by jaroslavtyc

Upgrade to PHP 8.0+ and Sylius 1.11 and 1.12

2024-01-04 14:38 UTC, ondrej-kuhnel approved these changes

2024-01-04 14:38 UTC, ondrej-kuhnel commented on CHANGELOG.md
> +## v2.1.0 (2023-01-04)
v1.1.0

2024-01-04 14:38 UTC, ondrej-kuhnel requested changes
Myslím že jen změna verze na 1.1.0

2024-01-04 14:51 UTC, jaroslavtyc commented on CHANGELOG.md
> +## v2.1.0 (2023-01-04)
Díky, fixnuto

2024-01-05 09:01 UTC, ondrej-kuhnel approved these changes

2024-01-05 09:14 UTC, merged